CREATE DATABASE QL_FASTFOOD;
GO

USE QL_FASTFOOD;
GO

-- 1. Chức Vụ
CREATE TABLE CHUC_VU (
    MaCV VARCHAR(20) PRIMARY KEY,
    TenCV NVARCHAR(100) NOT NULL,
    LuongCoBan BIGINT DEFAULT 0
);
GO

-- 2. Nhân Viên
CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR(20) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    SDT VARCHAR(20),
    DiaChi NVARCHAR(255),
    MatKhau VARCHAR(255) NOT NULL,
    TrangThai NVARCHAR(50),
    MaCV VARCHAR(20),
    FOREIGN KEY (MaCV) REFERENCES CHUC_VU(MaCV)
);
GO

-- 3. Ca Trực
CREATE TABLE CA_TRUC (
    MaCa VARCHAR(20) PRIMARY KEY,
    TenCa NVARCHAR(100) NOT NULL,
    GioBatDau TIME,
    GioKetThuc TIME,
    HeSoLuong FLOAT DEFAULT 1
);
GO

-- 4. Phân Công Ca
CREATE TABLE PHAN_CONG_CA (
    MaNV VARCHAR(20),
    MaCa VARCHAR(20),
    NgayLam DATE,
    PRIMARY KEY (MaNV, MaCa, NgayLam),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    FOREIGN KEY (MaCa) REFERENCES CA_TRUC(MaCa)
);
GO

-- 5. Loại Món
CREATE TABLE LOAI_MON (
    MaLoai VARCHAR(20) PRIMARY KEY,
    TenLoai NVARCHAR(100) NOT NULL
);
GO

-- 6. Đơn Vị Tính
CREATE TABLE DON_VI_TINH (
    MaDVT VARCHAR(20) PRIMARY KEY,
    TenDVT NVARCHAR(100) NOT NULL
);
GO

-- 7. Món Bán
CREATE TABLE MON_BAN (
    MaMon VARCHAR(20) PRIMARY KEY,
    TenMon NVARCHAR(200) NOT NULL,
    MaLoai VARCHAR(20),
    MaDVT VARCHAR(20),
    TrangThai NVARCHAR(50),
    FOREIGN KEY (MaLoai) REFERENCES LOAI_MON(MaLoai),
    FOREIGN KEY (MaDVT) REFERENCES DON_VI_TINH(MaDVT)
);
GO

-- 8. Đơn Vị Phục Vụ
CREATE TABLE DON_VI_PHUC_VU (
    MaDVPV VARCHAR(20) PRIMARY KEY,
    TenDVPV NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255)
);
GO

-- 9. Món Đơn Vị Phục Vụ
CREATE TABLE MON_DON_VI_PHUC_VU (
    MaMon VARCHAR(20),
    MaDVPV VARCHAR(20),
    DonGia DECIMAL(18, 2) DEFAULT 0,
    TrangThai NVARCHAR(50),
    PRIMARY KEY (MaMon, MaDVPV),
    FOREIGN KEY (MaMon) REFERENCES MON_BAN(MaMon),
    FOREIGN KEY (MaDVPV) REFERENCES DON_VI_PHUC_VU(MaDVPV)
);
GO

-- 10. Nguyên Liệu
CREATE TABLE NGUYEN_LIEU (
    MaNL VARCHAR(20) PRIMARY KEY,
    TenNL NVARCHAR(100) NOT NULL,
    DonViTinh NVARCHAR(50),
    SoLuongTon DECIMAL(18, 2) DEFAULT 0,
    GiaNhap DECIMAL(18, 2) DEFAULT 0,
    NguongToiThieu DECIMAL(18, 2) DEFAULT 0
);
GO

-- 11. Định Mức Món
CREATE TABLE DINH_MUC_MON (
    MaMon VARCHAR(20),
    MaDVPV VARCHAR(20),
    MaNL VARCHAR(20),
    SoLuongSuDung DECIMAL(18, 3) DEFAULT 0,
    PRIMARY KEY (MaMon, MaDVPV, MaNL),
    FOREIGN KEY (MaMon, MaDVPV) REFERENCES MON_DON_VI_PHUC_VU(MaMon, MaDVPV),
    FOREIGN KEY (MaNL) REFERENCES NGUYEN_LIEU(MaNL)
);
GO

-- 12. Khách Hàng
CREATE TABLE KHACH_HANG (
    MaKH VARCHAR(20) PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    SDT VARCHAR(20),
    DiemTichLuy INT DEFAULT 0
);
GO

-- 13. Hóa Đơn Bán
CREATE TABLE HOA_DON_BAN (
    MaHDB VARCHAR(20) PRIMARY KEY,
    NgayBan DATETIME DEFAULT GETDATE(),
    MaNV VARCHAR(20),
    MaKH VARCHAR(20),
    TongTien DECIMAL(18, 2) DEFAULT 0,
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
);
GO

-- 14. Chi Tiết Hóa Đơn Bán
CREATE TABLE CT_HOA_DON_BAN (
    MaHDB VARCHAR(20),
    MaMon VARCHAR(20),
    MaDVPV VARCHAR(20),
    SoLuong INT DEFAULT 1,
    PRIMARY KEY (MaHDB, MaMon, MaDVPV),
    FOREIGN KEY (MaHDB) REFERENCES HOA_DON_BAN(MaHDB),
    FOREIGN KEY (MaMon, MaDVPV) REFERENCES MON_DON_VI_PHUC_VU(MaMon, MaDVPV)
);
GO

-- 15. Nhà Cung Cấp
CREATE TABLE NHA_CUNG_CAP (
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255),
    SDT VARCHAR(20)
);
GO

-- 16. Hóa Đơn Nhập
CREATE TABLE HOA_DON_NHAP (
    MaHDN VARCHAR(20) PRIMARY KEY,
    NgayNhap DATETIME DEFAULT GETDATE(),
    MaNV VARCHAR(20),
    MaNCC VARCHAR(20),
    TongTien DECIMAL(18, 2) DEFAULT 0,
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC)
);
GO

-- 17. Chi Tiết Hóa Đơn Nhập
CREATE TABLE CT_HOA_DON_NHAP (
    MaHDN VARCHAR(20),
    MaNL VARCHAR(20),
    SoLuong DECIMAL(18, 2) DEFAULT 0,
    DonGia DECIMAL(18, 2) DEFAULT 0,
    PRIMARY KEY (MaHDN, MaNL),
    FOREIGN KEY (MaHDN) REFERENCES HOA_DON_NHAP(MaHDN),
    FOREIGN KEY (MaNL) REFERENCES NGUYEN_LIEU(MaNL)
);
GO

-- 18. Yêu Cầu
CREATE TABLE YEU_CAU (
    MaYeuCau INT IDENTITY(1,1) PRIMARY KEY,
    MaNV VARCHAR(20),
    LoaiYeuCau NVARCHAR(100),
    NoiDung NVARCHAR(MAX),
    NgayGui DATETIME DEFAULT GETDATE(),
    TuNgay DATE,
    DenNgay DATE,
    TrangThai INT DEFAULT 0,
    PhanHoiAdmin NVARCHAR(255)
);
GO
